FROM debian:jessie

ADD http://s3.amazonaws.com/influxdb/influxdb_0.8.3_amd64.deb /influxdb_0.8.3_amd64.deb
RUN dpkg -i /influxdb_0.8.3_amd64.deb

EXPOSE 8083 8086

CMD ["/opt/influxdb/current/influxdb", "-config=/opt/influxdb/current/config.toml"]
